version: '3.8'

services:
  postgresdb1:
    image: postgres:latest
    container_name: todos_db
    environment:
      POSTGRES_DB: todosDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data

  postgresdb2:
    image: postgres:latest
    container_name: todos_test_db
    environment:
      POSTGRES_DB: todosTestDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_main_data:
  postgres_test_data:
