INSERT INTO public.todos
(id, created_by, created_date, updated_by, modified_date, description, is_completed, title, is_deleted)
VALUES ('todo_2134356789abcdef', 'john.doe@example.com', now(), 'john.doe@example.com', now(),
        'Finish writing blog post.', false, 'Write blog post', false),
       ('todo_bcdef01234567890', 'john.doe@example.com', now(), 'john.doe@example.com', now(), 'Review code changes.',
        false, 'Review code', false),
       ('todo_567890abcdef1234', 'john.doe@example.com', now(), 'john.doe@example.com', now(),
        'Attend meeting with the sales team.', false, 'Attend meeting', false),
       ('todo_abcdef01234567f9', 'john.doe@example.com', now(), 'john.doe@example.com', now(), 'Go grocery shopping.',
        false, 'Go grocery shopping', false),
       ('todo_90abcdef0123r567', 'john.doe@example.com', now(), 'john.doe@example.com', now(), 'Pay bills.', false,
        'Pay bills', false),
       ('todo_0123456789abcdef', 'jane.doe@example.com', now(), 'jane.doe@example.com', now(), 'Finish writing report.',
        false, 'Write report', false),
       ('todo_abcdef01234567j9', 'jane.doe@example.com', now(), 'jane.doe@example.com', now(),
        'Create presentation for new client.', false, 'Create presentation', false),
       ('todo_90abcdef01233567', 'jane.doe@example.com', now(), 'jane.doe@example.com', now(),
        'Schedule appointments with customers.', false, 'Schedule appointments', false),
       ('todo_567890abcdeg1234', 'jane.doe@example.com', now(), 'jane.doe@example.com', now(),
        'Send email to team with updates on the project.', false, 'Send email', false),
       ('todo_1234356789abc4ef', 'jane.doe@example.com', now(), 'jane.doe@example.com', now(), 'Clean up desk.', false,
        'Clean up desk', false),
       ('todo_abcdef0123456739', 'peter.parker@example.com', now(), 'peter.parker@example.com', now(),
        'Finish coding up new feature.', false, 'Code new feature', false),
       ('todo_90abcdef01234567', 'peter.parker@example.com', now(), 'peter.parker@example.com', now(), 'Debug code.',
        false, 'Debug code', false),
       ('todo_567890abcdee1234', 'peter.parker@example.com', now(), 'peter.parker@example.com', now(),
        'Deploy code to production.', false, 'Deploy code', false),
       ('todo_1234356789abcdef', 'peter.parker@example.com', now(), 'peter.parker@example.com', now(),
        'Write unit tests.', false, 'Write unit tests', false),
       ('todo_abcdef0123456709', 'peter.parker@example.com', now(), 'peter.parker@example.com', now(), 'Refactor code.',
        false, 'Refactor code', false),
       ('todo_0123456789abc7ef', 'mary.jane@example.com', now(), 'mary.jane@example.com', now(),
        'Design new marketing campaign.', false, 'Design marketing campaign', false),
       ('todo_abcdef0123456719', 'mary.jane@example.com', now(), 'mary.jane@example.com', now(),
        'Write copy for new landing page.', false, 'Write landing page copy', false);
